### PR TITLE
Added comments about what tests do.

### PR DESCRIPTION
**Pull request by ishengyang**

### CODE REVIEW

**Comment by mhvk** [comment]
@ishengyang - now looking at the differences, I noticed that one change that I made in my branch was to call the file `SAMPLE_M5B` instead of `SAMPLE_FILE` (since there are other samples too). So, I think one needs to redo that change here and remove `SAMPLE_FILE`.

The process is:
```
git checkout working-on-cita
# edit test_conversion.py
git commit -a
# write short commit message
python setup.py test
# checks that the test code still works
git push
# which will put it in your branch on github, and rerun the tests.
```

**Comment by ishengyang** [comment]
Hi Marten,

Sorry I am still not familiar enough with this.
I am not entirely sure about how to follow that instruction.

Are those messages after # purely for explanation?
I operated under that assumption and it told me nothing to commit to.

I assume I should change that SAMPLE_M5B to SAMPLE_FILE manually, right?
Namely, the second line of your instruction should not be a comment, but is
really me editing that file to the correct version?

cheers,
I-Sheng.

**Comment by mhvk** [comment]
> I assume I should change that SAMPLE_M5B to SAMPLE_FILE manually, right? Namely, the second line of your instruction should not be a comment, but is really me editing that file to the correct version?

Yes, that is correct, the second line is you actually doing editing. But please change `SAMPLE_FILE` to `SAMPLE_M5B` in the code (and remove the definition of `SAMPLE_FILE` near the top).

**Comment by ishengyang** [comment]
yeah, just did that but stuck twice in the commit message.....
what's the magic key to end it?

**Comment by ishengyang** [comment]
nvm, I redid it and add the message directly in command line by -m.
How long does the testing process usually take?
It seems to be stuck.......

**Comment by ishengyang** [comment]
ok, test completed and git push successful.
My browser viewing github did not update change though, after many reloads.
Maybe I should just be more patient.

**Comment by mhvk** [comment]
@ishengyang - something must have gone wrong with the `git push` since there are no changes here....

**Comment by mhvk** [comment]
@ishengyang - A long time ago you made a pull request to baseband to improve the documentation of the conversion test. By now, I had gone too far ahead to make this easy to apply, so I've now copied the text by hand in https://github.com/mhvk/baseband/pull/26/commits/206ffcfaf69c0c087b27cde5d896c5f77ac76cd8. So, closing this one.

**Pull request closed without merging**
