### PR TITLE
fixed bug with maximum definition and argument pass...

### PR DESCRIPTION
**Pull request by cczhu**
… in VDIFStreamReader.header1().  Also fixed a typo in base.py.

### CODE REVIEW

**Comment by mhvk** [comment]
The changes are all OK, but a test that checked whether `header1` gave an error now fails to do so because it now doesn't add enough crap.

**Comment by cczhu** [comment]
This is actually a more interesting problem - the test TestVDIF.test_corrupt_stream failed because the way a bunch of extra data was added was using

            for i in range(15):
                frame2.tofile(s)

The problem with this is because it has the same frame_nr as frame, f2.nthread is always larger than the value than the number we add into range (i.e. the more crap you add, the further header1's getter now looks backward.  It's therefore no longer possible to fail in the way the test is written.

On a related note, for files where frame_nr = 0 for all frames, using

      maximum = 2*self.nthread*self.header0.framesize

could potentially lead to an infinite loop because maximum is larger than raw_size, though only if you corrupt header0's thread ID (otherwise you'll just find the same frame header0 came from).  The solution (if a solution is even needed) would be to do

        maximum = min(2*self.nthread*self.header0.framesize, 
                        raw_size - self.header0.framesize)

But this leads to the question of whether or not header1 should be allowed to equal header0.  What if we only have one frame_nr, and many threads?

**Comment by cczhu** [comment]
I modified TestVDIF.test_corrupt_stream() to append the last frame of the sample file repeatedly (rather than the second) - this produces a corrupt stream that breaks header1 finding.

**Comment by mhvk** [comment]
Looks all OK! Merging...

**Pull request merged**
