### PR TITLE
Adding Mark4 sample data from Fortleza(Ft) station

### PR DESCRIPTION
**Pull request by shaoguangleo**
With the following format
- channels = 16
- bps = 2
- fanout = 2

### CODE REVIEW

**Comment by shaoguangleo** [comment]
I just split 256KB data of the original file for the following test.

**Comment by mhvk** [comment]
@shaoguangleo - thanks! I can find the header but it turns out to be so far into the file that there isn't a full frame inside. So, could I bother you to replace the file with a 320kiB extract?

**Comment by mhvk** [comment]
Also, just to ensure I don't screw up, what is the sample rate?

**Comment by mhvk** [comment]
Hmm, the header is a bit odd, with 14 USB channels and 1 LSB, and the sign and magnitude bits assigned differently than what is expected by `mark5access`. It might be good to check the `vex`/`vix` file, if you have one. (Or any other way to know "ground truth" - I'll see if the payload statistics help.)

**Comment by shaoguangleo** [comment]
@mhvk yeah, of cource, I will replace a new one, as far as I know, the data rate is 1Gbps.
I can send you the vex file if you need it.

**Comment by mhvk** [comment]
@shaoguangleo - sorry for the VERY long delay, but I got back to baseband as I'm hoping to have a 3.1 version out, and your issue is here I would certainly like to have solved for it!  I think the vix file would indeed be useful, just to double-check the track assignments. Of course, if in the meantime you managed to read it with other software, do let me know - I'm definitely all for not reinventing wheels!

**Comment by shaoguangleo** [comment]
@mhvk Dear Marten, Do no worry for this.
As we had figure it out by change some code in DiFX where decoding the baseband data.
Every time when we processing the Ft station, we will check out the special version.
So I think it is also need in your baseband software.

I think we can close this PR if you agree.

**Comment by mhvk** [comment]
Actually, I wouldn't mind ensuring this works in baseband out of the box, so if you know how the tracks were assigned (or can point me to the patch to DifX and/or the vix files), that would be nice.

**Comment by mhvk** [comment]
@shaoguangleo - if you have a chance, would you mind letting me know how the tracks were assigned? It is also fine to point me to the patch to DifX and/or the vix files. Thanks!

**Comment by shaoguangleo** [comment]
@mhvk I just check the special version for Ft station, we just make some modification in the file mark5_format_mark4.c in DiFX, which should correspond the payload.py in Mark4, I've made some modification on my master branch, hope can help.

The different should at following:
original version:
```c
#define reorder64(x) ((((x) & 0xAA55AA55AA55AA55ULL)) | \
                        (((x) & 0x5500550055005500ULL) >> 7) | \      
                        (((x) & 0x00AA00AA00AA00AAULL) << 7))       
```

Modify version:

```c
#define reorder64(x) ((((x) & 0xFFFFFAAFFFFFFAAFULL)) | \   
                            (((x) & 0x0000050000000500ULL) >> 4) | \   
                            (((x) & 0x0000005000000050ULL) << 4))
```

**Comment by mhvk** [comment]
@shaoguangleo - thanks so much, that is very useful! Happily, it is exactly the change I had made myself in a test branch, as it corresponds to how the sign and magnitude bits are supposed to be stored according to the headers in the file. But obviously I wasn't sure it was actually correct!

So, I guess my bottom line is that I shouldn't just presume that mark5access is ground truth, but instead check the full configuration. It may even possible to create reordering functions like the one you gave on the fly.  Anyway, definitely not as easy as I thought initially, but if I get this right, baseband will really be able to read all mark 4 data! So, thanks so much for reporting.

**Comment by mhvk** [comment]
Closing this PR, since I am building on it in #380 in a separate branch (which uses the two commits here). Thanks again for reporting and finding the basics of the fix, @shaoguangleo!

**Pull request closed without merging**
