### PR TITLE
Test on windows

### LINKED ISSUE #376: Baseband tests fail on Windows due to OSError
Currently, baseband does not pass tests on Windows systems purely due to poor management of file paths in some tests.

The error log can be found here: https://gist.github.com/theXYZT/9bd177424cdff9e90fb2b43afaf28e1e

One example of poor path management would be the first error in `baseband/dada/tests/test_dada.py` line 251 where a new filename is created via: `filename = str(tmpdir.join('a.dada'))` which immediately fails when used in `open()` on any system not using POSIX-style paths. Quickly skimming through the errors, they all seem to occur when a similar `string.join` operation is used to make paths.

A simple solution would be to use `pathlib`  and convert string-based paths to proper Path objects: 
```
from pathlib import Path
filename = Path(filename)
```

Optionally, we could also use this in the package itself in the following two files: `baseband/helpers/sequentialfile.py` and `baseband/vlbi_base/base.py` so that you don't have change the way you write tests.

---

Note: The above tests were done using `baseband.test()`. I also ran `tox -e test` on the source code and got similar errors.

### PR DESCRIPTION
**Pull request by mhvk**
Fixing the guppi test that was mentioned in #376, as well as similar tests in DADA. May have left one...

fixes #376

This possibly should be a cron only test.

### CODE REVIEW

**Comment by mhvk** [comment]
@theXYZT - I put a travis windows test on, and fixed the file overwriting issues in #376, but there are some issues left. The GSB ones I think are fixable just by allowing a difference in number of characters for a linebreak, but the one with the sequential file template is more puzzling (see especially the documentation failure at the end of the travis log). Does windows not allow filenames with `:` in it? Any ideas?

**Comment by theXYZT** [comment]
Ah yes! Special characters are forbidden in file names, haha. It's frustrating because we like to use ISOT time formats in filenames.

**Comment by mhvk** [comment]
OK, so perhaps I should just `xfail` those tests on windows...

**Comment by mhvk** [comment]
OK, on windows I now skip the DADA tests/docs that use `:` in the filenames, and fixed the line length calculations on GSB which were also failing. With this, everything passes, and we now have a test against regressions. So, merging! Thanks, @theXYZT!

**Pull request merged**
