### PR TITLE
Solve inability to read GUPPI/VEGAS keywords written as strings

### PR DESCRIPTION
**Pull request by jeanlucmargot**
The existing baseband code handles GUPPI header cards/keywords written in the format
NBITS  =          8
However, modern instruments, such as VEGAS, write header cards/keywords in the format
NBITS  = '8    '
This update to baseband/guppi/header.py enables reading both kinds of headers.

### CODE REVIEW

**Review by mhvk — COMMENTED** [review]
@jeanlucmargot - thanks for the PR! This looks good, but could you add tests? This would involve adding a sample file to `baseband.data` -- see `__init__.py` to get an idea of how this was done for other files. In this case, just a single head with a bit of data might suffice. And then add tests to `tests/test_guppi.py`

**Comment by jeanlucmargot** [comment]
@mhvk Thank you.  I added a simple test.

**Review by mhvk — COMMENTED** [review]
This looks good in principle, but I meant the tests to be added to the existing `baseband/guppi/tests/test_guppi.py`. (Though if you just want to call it `baseband/guppi/tests/test_vegas.py` that would be fine too.)

Anyway, will run the tests now just so we know there are no problems.

**Review by mhvk — APPROVED** [review]
@jeanlucmargot - I made the few remaining edits and style fixes, and pushed them to your branch. Assuming tests pass, this should be all good to go, so I'll merge. Thanks for the fix!!

**Comment by mhvk** [comment]
I also made a new bug-fix release, since it might as well work for everyone immediately.

**Pull request merged**
