### PR TITLE
Temporarily fix pytest to <= 3.2, since 3.3 is buggy with astropy 2.0

### PR DESCRIPTION
**Pull request by mhvk**
@cczhu - trying if this helps, so we can move on

### CODE REVIEW

**Comment by mhvk** [comment]
Sadly, this doesn't help at all.

**Comment by mhvk** [comment]
OK, needed to adjust `.travis.yml` - getting there.

**Comment by mhvk** [comment]
Fixed. @cczhu - Will merge now so you can rebase the astropy-helpers one and then the rest.

**Comment by cczhu** [comment]
Thanks, it works now!  I've uploaded the new renaming of time0.

Charles

**Pull request merged**
